export const NAVIGATION = {
  login: 'Login',
  forgot: 'ForgotPassword',
  register: 'Register',
  home: 'Home',
  profile: 'Profile',
  cart:'Your Order',
  settings:'Settings',
  category:'Category',
  subCategory:'SubCategory',
  productCatalog:'ProductCatalog',
  productDetails:'ProductDetails',
  changePassword:'ChangePassword',
  wishList:'Wishlist',
  search:'Search',
  account:'Account',
  generalInfo:'GeneralInfo',
  cardsDetails:'Cards',
  editCard:'EditCard',
  address:'Address',
  editAddress:'EditAddress',
  checkOut:'CheckOut',
  paymentOption:"PaymentOption",
  reviewOrder:'ReviewOrder',
  thankYou:'ThankYou',
  registry:'Registry',
  orders:'Orders',
  orderDetails:'OrderDetails',
  trackOrders:'TrackOrders',
  coins:'Coins',
  myCoupons:'myCoupons',
  subscriptions:'subscriptions',
  loginSec:'LoginSecurity',
  changePassword:'ChangePassword',
  support:'Support',
  subCategories:'SubCategories',
  childCategories:'ChildCategories',
  paymentView:"PaymentView",
  subChildProducts:'SubChildProducts',
  jikapuFresh:'JikapuFresh',
  addRegistryAddress:'AddRegistryAddress',
  paymentMethod:'PaymentMethod',
  jFreshCart:'JikapuFreshCart',
  jikapuStore:'JikapuStore',
  jikapuCategory:'JikapuCategory',
  addNewAddress:'AddAddress',
  secureAccount:'SecureAccount'
};
